<?php

/**
 * Laravel-admin - admin builder based on Laravel.
 * @author z-song <https://github.com/z-song>
 *
 * Bootstraper for Admin.
 *
 * Here you can remove builtin form field:
 * Encore\Admin\Form::forget(['map', 'editor']);
 *
 * Or extend custom form field:
 * Encore\Admin\Form::extend('php', PHPEditor::class);
 *
 * Or require js and css assets:
 * Admin::css('/packages/prettydocs/css/styles.css');
 * Admin::js('/packages/prettydocs/js/main.js');
 *
 */


use App\Models\Utils;
use Encore\Admin\Facades\Admin;
use Illuminate\Support\Facades\Auth;
use App\Admin\Extensions\Nav\Shortcut;
use App\Admin\Extensions\Nav\Dropdown;
use App\Models\AdminRoleUser;
use App\Models\AttendanceRecord;
use App\Models\Department;
use App\Models\User;
use App\Models\Vehicle;
use App\Models\VehicleRequest;
use Carbon\Carbon;
use Encore\Admin\Form;
use Illuminate\Support\Facades\DB;
use App\Services\AccessControlService;
use App\Admin\Extensions\PermissionChecker;


// The house style (public/css/ehrms.css: white, square, maroon) is linked in
// resources/views/vendor/admin/index.blade.php, after laravel-admin's own
// stylesheets — Admin::css() would print it before Bootstrap and AdminLTE,
// which would then override it. It replaces the earlier muni-ehrms.css /
// custom-dashboard.css theme and the Bootstrap 4 sheet, which clashed with
// laravel-admin's Bootstrap 3.

// Daily attendance placeholder records are generated by the scheduler (see App\Console\Kernel)

// Access to pages and the sidebar menu come from App\Services\AccessPolicy
// (see AdminRoleMiddleware and resources/views/vendor/admin/partials/sidebar).
//
// Note: laravel-admin fires Admin::booting() callbacks before it loads this
// file, so callbacks registered here with Admin::booting() never run on a
// normal request. Register things directly instead.

// Staff departments, roles and Terminal IDs are maintained under Employees
// (App\Admin\Controllers\UsersController).

// Every form: Submit and Reset only. The "View / Continue creating / Continue
// editing" checkboxes add noise and are rarely what anyone wants.
Form::init(function (Form $form) {
    $form->footer(function ($footer) {
        $footer->disableViewCheck();
        $footer->disableEditingCheck();
        $footer->disableCreatingCheck();
    });
});
